### ISSUE TITLE
`statespace` Roadmap: Enhancements and known bugs

### ISSUE THREAD

**Issue by jessegrabowski** [pymc-devs/pymc-experimental#230]
A to-do list of things that still need to be done on the statespace models, to organize future PRs. Anyone is free to add to the list.

- [ ] Generate IRFs for observable variables in addition to the hidden states
- [ ] Allow post-estimation stuff (IRF, forecasting) for models with exogenous variables (**high priority**)
- [ ] Add `k_endog` argument to `structrual.Component`s to enable multivariate structural models (**high priority**)
- [ ] Flag on `Component`s to allow users to pass full state covariance matrix if desired (important for the MV case, potentially interesting in univariate case too) (**high priority**)
- [ ] Add Additive Holt-Winters Exponential Smoothing models, see [here](https://www.statsmodels.org/stable/examples/notebooks/generated/ets.html)
- [ ] Add dampening parameters to trend/seasonal components?
- [ ] Better/more consistent names for the parameters of each `Component`?
- [ ] Improve how dims/coords are generated/handled? 
- [ ] Improve/standardize `Component` tests
- [ ] Performance: Explore Chandrasekhar recursions for univariate models (see [here](https://www.statsmodels.org/stable/examples/notebooks/generated/statespace_chandrasekhar.html)
- [ ] Performance: Inside the Kalman Filter scan, it possible to detect convergence and use the steady-state covariance matrix (and it's inverse)? Huge compute savings for large statespace/long time-series if so.
- [ ] Performance: JAX implementations of `SolveDiscreteARE` and `SolveDiscreteLyapunov`

**Comment by ferrine** [comment]
is it possible to create a prior distribution that follows the state space model as it is done with GPs?

**Comment by jessegrabowski** [comment]
Yes, I think it should be. I added this functionality as a to-do item.
